### ISSUE TITLE
apply colab badge action

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/nmisp#202]
## marketplace 
https://github.com/marketplace/actions/colab-badge-action

## sample
``` yaml
name: Example Workflow
on: [push]

jobs:
  badges:
    name: Example Badge Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: "all"
          target_branch: main
          target_repository: user/user-repo
          update: true

      - name: Use your favorite commit&push action here
        uses: action/commit@push
        with: ...
```

## remaining question
* how to commit & push in github actions?
* https://github.com/marketplace/actions/git-auto-commit seems the most installed ?
