### ISSUE TITLE
Travis-CI cache without a default environment

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/nmisp#40]
* Test result [link](https://www.travis-ci.org/kangwonlee/nmisp/jobs/509891245)
* Currently c85c592 caches followings:

``` yaml
cache :
  directories:
    - $HOME/download
    - $HOME/miniconda
    - $HOME/AppData/Local/Temp/chocolatey
```

* Which folder contains the `conda` default environment info?'
* [NoBaseEnvironmentError](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id28) seems relatively new
